### ISSUE TITLE
Dependency Dashboard

### ISSUE THREAD

**Issue by hervyt** [OpenBAS-Platform/injectors#26]
This issue lists Renovate updates and detected dependencies. Read the [Dependency Dashboard](https://docs.renovatebot.com/key-concepts/dashboard/) docs to learn more.

## Open

These updates have all been created already. Click a checkbox below to force a retry/rebase of any.

 - [ ] [Update cimg/python Docker tag to v3.12](../pull/25)

## Detected dependencies

<details><summary>circleci</summary>
<blockquote>

<details><summary>.circleci/config.yml</summary>

 - `slack 4.13.3`
 - `ms-teams 0.0.1`
 - `cimg/python 3.11`

</details>

</blockquote>
</details>

<details><summary>docker-compose</summary>
<blockquote>

<details><summary>http-query/docker-compose.yml</summary>

 - `openbas/injector-http-query 1.1.1`

</details>

</blockquote>
</details>

<details><summary>dockerfile</summary>
<blockquote>

<details><summary>http-query/Dockerfile</summary>

 - `python 3.12-alpine`

</details>

</blockquote>
</details>

<details><summary>pip_requirements</summary>
<blockquote>

<details><summary>http-query/src/requirements.txt</summary>

 - `pyobas ==1.1.1`

</details>

</blockquote>
</details>

**Comment by guillaumejparis** [comment]
We already got https://github.com/OpenBAS-Platform/injectors/issues/1
